name: test

on: [push, pull_request]

jobs:
  pre-tutorial-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
    - name: "Install requirements"
      run: |
        conda env create --file environment.yml
        $CONDA/bin/activate qutip-tutorial-env
    - name: "Install testing utilities"
      run: |
        pip install pytest nbmake
    - name: Run pre-tutorial notebook test
      run: |
        jupyter kernel &
        pytest --nbmake pre-tutorial-test.ipynb --overwrite --nbmake-timeout=500
