name: test

on: [push, pull_request]

jobs:
  pre-tutorial-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: qutip-tutorial-env
          environment-file: ./environment.yml
    - name: "Install pytest and nbmake"
      run: |
        pip install pytest nbmake
    - name: Run pre-tutorial notebook test
      run: |
        jupyter kernel &
        pytest --nbmake pre-tutorial-test.ipynb --nbmake-timeout=500
