name: test

on: [push, pull_request]

defaults:
  run:
    shell: bash -l {0}

jobs:
  pre-tutorial-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
          environment-file: environment.yml
          activate-environment: qutip-tutorial-env
          auto-activate-base: false
          python-version: "3.9"
    - name: "Environment informaton"
      run: |
        python -V
        conda info
        conda list
        python -c "import qutip; qutip.about()"
    - name: "Install pytest and nbmake"
      run: |
        pip install pytest nbmake
    - name: Run pre-tutorial notebook test
      run: |
        jupyter kernel &
        pytest --nbmake pre-tutorial-test.ipynb --nbmake-timeout=500
