name: test

on: [push, pull_request]

jobs:
  pre-tutorial-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
          activate-environment: qutip-tutorial-env
          python-version: 3.9
          environment-file: ./environment.yml
          auto-activate-base: false
    - name: "Environment informaton"
      run: |
        python -V
        conda env list
        conda list
        python -c "import qutip; qutip.about()"
    - name: "Install pytest and nbmake"
      run: |
        pip install pytest nbmake
    - name: Run pre-tutorial notebook test
      run: |
        jupyter kernel &
        pytest --nbmake pre-tutorial-test.ipynb --nbmake-timeout=500
